site_name: Scopie
site_url: https://scopie.dev
site_author: Ronnie Smith
site_description: >-
  Extendable authorization with your own data.

repo_url: https://github.com/miniscruff/scopie
repo_name: miniscruff/scopie
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep orange
      accent: cyan
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: cyan
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.top
    - search.suggest
    - content.code.copy
    - content.code.annotate 
  icon:
    repo: simple/github
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Specification:
      - specification/index.md
      - Terms: specification/terms.md
      - Functions: specification/functions.md
      - Errors: specification/errors.md
      - Logic: specification/logic.md
      - BNF: specification/bnf.md
  - Examples:
      - examples/index.md
      - Blog: examples/blog.md
  - Implementations: implementations.md
